<%@ Page Title="" Language="C#" MasterPageFile="~/WebPages/Main.Master" AutoEventWireup="true" CodeBehind="ViewOrders.aspx.cs" Inherits="Eshopping.WebPages.ViewOrders" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container">
  <h1>Your Recent Orders&nbsp;&nbsp; </h1>
        <p>
            <asp:Label ID="Label1" runat="server" Font-Size="Large" Text="Total Bill - "></asp:Label>
&nbsp;&nbsp;
            <asp:Label ID="bill1" runat="server" Font-Bold="True" Font-Size="Medium" Text="Rs."></asp:Label>
            <asp:Label ID="bill" runat="server" Font-Bold="True" Font-Size="Medium" Text="0"></asp:Label>
        &nbsp;<asp:Label ID="bill0" runat="server" Font-Bold="True" Font-Size="Medium" Text=" /PKR"></asp:Label>
        </p>
        <p>
            <asp:Button ID="Button1" runat="server" CssClass="btn btn-primary" OnClick="Button1_Click" Text="Confirm Order" />
        </p>
    <hr />
    </div>
    <br />
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" CssClass="table table-responsive table-hover" DataKeyNames="Item_ID" DataSourceID="SqlDataSource1" GridLines="None">
            <Columns>
                <asp:BoundField DataField="quant" HeaderText="Item Quantity" SortExpression="quant" />
                <asp:BoundField DataField="Customer_Name" HeaderText="Customer Name" SortExpression="Customer_Name" ReadOnly="True" />
                <asp:BoundField DataField="Item_ID" HeaderText="Item ID" SortExpression="Item_ID" InsertVisible="False" ReadOnly="True" />
                <asp:BoundField DataField="Item_Name" HeaderText="Item Name" SortExpression="Item_Name" ReadOnly="True" />
                <asp:BoundField DataField="Item_Price" HeaderText="Item Price" SortExpression="Item_Price" ReadOnly="True" />
                <asp:ImageField DataImageUrlField="item_image" HeaderText="Item Image" ControlStyle-Height="200px" ReadOnly="True">
<ControlStyle Height="200px"></ControlStyle>
                </asp:ImageField>
            </Columns>
        </asp:GridView>
            </div>
           
        </div>
       
        <br />

    </div>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ordrs %>" SelectCommand="SELECT Cust_orders.quant, Customer.Customer_Name, Product.Item_ID,Product.Item_Name, Product.Item_Price, Product.item_image FROM Cust_orders INNER JOIN Customer ON Cust_orders.cust_id = Customer.Customer_ID INNER JOIN Product ON Cust_orders.Item_id = Product.Item_ID WHERE (Cust_orders.cust_id = @cust_id)" DeleteCommand="DELETE FROM Cust_orders WHERE Item_id=@Item_ID">
                <DeleteParameters>
                    <asp:Parameter Name="Item_ID" />
                </DeleteParameters>
                <SelectParameters>
                    <asp:SessionParameter Name="cust_id" SessionField="Cust_id" Type="Int32" />
                </SelectParameters>
</asp:SqlDataSource>

    <br />

</asp:Content>
